"use client";

import { useState, useEffect } from "react";
import { Sparkles, Cpu, Key, Sliders, Globe, Activity } from "lucide-react";
import PostGeneratorForm from "@/components/PostGeneratorForm";
import ResultsDisplay from "@/components/ResultsDisplay";
import AgentPlayground from "@/components/AgentPlayground";
import SettingsTab from "@/components/SettingsTab";

interface Variant {
  id: number;
  style: string;
  content: string;
  score: number;
  critique: string;
}

interface GenerationResult {
  best: Variant;
  drafts: Variant[];
}

interface Agent {
  id: string;
  name: string;
  provider: string;
  model: string;
  systemPrompt: string;
  temperature: number;
  enabled: boolean;
}

interface JudgeConfig {
  provider: string;
  model: string;
  systemPrompt: string;
  temperature: number;
}

interface ApiKeys {
  gemini: string;
  openai: string;
  anthropic: string;
  openrouter: string;
  ollamaUrl: string;
  lmStudioUrl: string;
  customBaseUrl: string;
  customApiKey: string;
}

const DEFAULT_AGENTS: Agent[] = [
  {
    id: "storytelling-ghost",
    name: "Storyteller Persona",
    provider: "gemini",
    model: "gemini-2.5-flash",
    systemPrompt: "You are a warm, engaging storytelling ghostwriter. Focus on a narrative structure, lessons learned, vulnerability, personal growth, and emotional connection. Keep paragraphs short and use a hook that makes the reader stop scrolling.",
    temperature: 0.85,
    enabled: true,
  },
  {
    id: "analytical-growth",
    name: "Analytical Growth Hacker",
    provider: "openai",
    model: "gpt-4o-mini",
    systemPrompt: "You are a strict, analytical copywriter. Write a post focused on concrete metrics, templates, systems, lists, checklists, and bullet points. Focus on business value and clear takeaways. Avoid fluff.",
    temperature: 0.25,
    enabled: true,
  },
  {
    id: "contrarian-tech-rebel",
    name: "Contrarian Industry Rebel",
    provider: "anthropic",
    model: "claude-3-5-sonnet-20241022",
    systemPrompt: "You are a contrarian expert. Challenge standard advice in tech and business. Focus on counter-intuitive hooks, logical explanations, and why standard processes are broken. Keep it punchy.",
    temperature: 0.75,
    enabled: true,
  },
];

const DEFAULT_JUDGE: JudgeConfig = {
  provider: "gemini",
  model: "gemini-2.5-flash",
  systemPrompt: "You are a world-class social media strategist acting as a Master Judge. Your task is to analyze the drafts generated by multiple agent writers, compare their hooks, formatting styles, and narratives, and synthesize them into the absolute best possible LinkedIn post. Critique the result and highlight why it combines the best elements of the drafts.",
  temperature: 0.5,
};

const DEFAULT_KEYS: ApiKeys = {
  gemini: "",
  openai: "",
  anthropic: "",
  openrouter: "",
  ollamaUrl: "http://localhost:11434",
  lmStudioUrl: "http://localhost:1234",
  customBaseUrl: "",
  customApiKey: "",
};

export default function Home() {
  const [activeTab, setActiveTab] = useState<"workspace" | "agents" | "settings">("workspace");
  const [apiKeys, setApiKeys] = useState<ApiKeys>(DEFAULT_KEYS);
  const [agents, setAgents] = useState<Agent[]>(DEFAULT_AGENTS);
  const [judgeConfig, setJudgeConfig] = useState<JudgeConfig>(DEFAULT_JUDGE);
  const [result, setResult] = useState<GenerationResult | null>(null);
  const [loaded, setLoaded] = useState(false);

  // Sync state from LocalStorage on mount
  useEffect(() => {
    const keysData = localStorage.getItem("vm_api_keys");
    const agentsData = localStorage.getItem("vm_agents_config");
    const judgeData = localStorage.getItem("vm_judge_config");

    if (keysData) {
      try { setApiKeys(JSON.parse(keysData)); } catch (e) {}
    }
    if (agentsData) {
      try { setAgents(JSON.parse(agentsData)); } catch (e) {}
    }
    if (judgeData) {
      try { setJudgeConfig(JSON.parse(judgeData)); } catch (e) {}
    }
    setLoaded(true);
  }, []);

  const updateApiKeys = (newKeys: ApiKeys) => {
    setApiKeys(newKeys);
    localStorage.setItem("vm_api_keys", JSON.stringify(newKeys));
  };

  const updateAgents = (newAgents: Agent[]) => {
    setAgents(newAgents);
    localStorage.setItem("vm_agents_config", JSON.stringify(newAgents));
  };

  const updateJudge = (newJudge: JudgeConfig) => {
    setJudgeConfig(newJudge);
    localStorage.setItem("vm_judge_config", JSON.stringify(newJudge));
  };

  const handleToggleAgent = (id: string) => {
    const updated = agents.map((a) => (a.id === id ? { ...a, enabled: !a.enabled } : a));
    updateAgents(updated);
  };

  if (!loaded) {
    return (
      <div className="flex h-screen w-screen items-center justify-center bg-[#050508]">
        <Activity className="animate-spin text-rose-500" size={32} />
      </div>
    );
  }

  const activeAgentsCount = agents.filter((a) => a.enabled).length;

  return (
    <div className="dashboard-layout">
      {/* 3-Panel: Panel 1 - Sidebar Navigation */}
      <aside className="sidebar">
        <div className="brand-text">
          <div className="flow-step-icon active" style={{ width: "32px", height: "32px", border: "1px solid var(--accent)" }}>
            <Sparkles size={16} />
          </div>
          <span>
            Virality <span className="serif-italic" style={{ color: "var(--accent)" }}>Mapper</span>
          </span>
        </div>

        <nav style={{ flex: 1 }}>
          <div
            className={`nav-item ${activeTab === "workspace" ? "active" : ""}`}
            onClick={() => setActiveTab("workspace")}
          >
            <Sparkles size={16} />
            <span>Workspace</span>
          </div>
          <div
            className={`nav-item ${activeTab === "agents" ? "active" : ""}`}
            onClick={() => setActiveTab("agents")}
          >
            <Sliders size={16} />
            <span>Agent Playground</span>
          </div>
          <div
            className={`nav-item ${activeTab === "settings" ? "active" : ""}`}
            onClick={() => setActiveTab("settings")}
          >
            <Key size={16} />
            <span>Settings</span>
          </div>
        </nav>

        {/* Sidebar Info/Stats Widget */}
        <div className="glass-panel p-4 flex flex-col gap-2" style={{ background: "rgba(255,255,255,0.01)" }}>
          <div className="flex items-center gap-1.5 text-xs font-semibold text-zinc-400">
            <Activity size={12} style={{ color: "var(--accent)" }} />
            <span>Active Status</span>
          </div>
          <div className="flex justify-between text-xs text-zinc-500">
            <span>Enabled Agents:</span>
            <span style={{ color: activeAgentsCount >= 2 ? "var(--accent)" : "#fca5a5", fontWeight: 700 }}>
              {activeAgentsCount}
            </span>
          </div>
          <div className="flex justify-between text-xs text-zinc-500">
            <span>Judge Agent:</span>
            <span style={{ color: "white" }}>
              {judgeConfig.provider.toUpperCase()}
            </span>
          </div>
        </div>
      </aside>

      {/* 3-Panel: Panel 2 - Content Dashboard */}
      <main className="main-content">
        <header style={{ borderBottom: "1px solid var(--panel-border)", padding: "16px 32px", background: "rgba(5, 5, 8, 0.8)", position: "sticky", top: 0, zIndex: 10 }}>
          <div className="flex items-center justify-between max-w-6xl mx-auto">
            <h1 style={{ fontSize: "1.25rem", fontWeight: 800 }}>
              {activeTab === "workspace" && "Writing Console"}
              {activeTab === "agents" && "Agent Customizer"}
              {activeTab === "settings" && "Credentials Manager"}
            </h1>
            <div className="status-bar" style={{ margin: 0, padding: "4px 10px" }}>
              <span className="status-dot"></span>
              <span>Consensus Engine V2</span>
            </div>
          </div>
        </header>

        <div className="container" style={{ padding: "32px 32px 48px", overflowY: "auto" }}>
          {activeTab === "workspace" && (
            <div className="flex flex-col gap-6">
              <PostGeneratorForm
                agents={agents}
                judgeConfig={judgeConfig}
                apiKeys={apiKeys}
                onGenerate={(data) => setResult(data)}
                onToggleAgent={handleToggleAgent}
              />
              {result && <ResultsDisplay result={result} />}
            </div>
          )}

          {activeTab === "agents" && (
            <AgentPlayground
              agents={agents}
              judgeConfig={judgeConfig}
              apiKeys={apiKeys}
              onUpdateAgents={updateAgents}
              onUpdateJudge={updateJudge}
            />
          )}

          {activeTab === "settings" && (
            <SettingsTab
              apiKeys={apiKeys}
              onSave={updateApiKeys}
            />
          )}
        </div>
      </main>
    </div>
  );
}
